### ISSUE TITLE
Something is weird with Trinkets in 1.17.1

### ISSUE THREAD

**Issue by Desempregago** [emilyalexandra/trinkets#105]
[Crash Report](https://pastebin.com/3nuDMELF)

Minecraft 1.17.1
Trinkets 3.0.0 (1.17 release)

**Comment by craftish37** [comment]
<img width="852" alt="Capture d’écran 2021-07-09 à 00 16 58" src="https://user-images.githubusercontent.com/63811617/124997486-fd7d9680-e04a-11eb-9cf4-3acacbcf6ab2.png">
Update your mods, then if there's again problems, ask again 👀

**Comment by Fogrits** [comment]
These mods have nothing to do with Trinkets.

**Comment by craftish37** [comment]
You know that if all the plugins aren't in a compatible version, any of them will works ?

**Comment by Fogrits** [comment]
I know, but my problem is related to Trinkets

**Comment by emilyalexandra** [comment]
This is known, a fix is being worked on

**Comment by emilyalexandra** [comment]
Fixed in 3.0.1
