### ISSUE TITLE
Crash when picking up xp

### ISSUE THREAD

**Issue by SollyW** [emilyalexandra/trinkets#107]
If a player picks up an experience orb with no equipment - including an empty hand - the game crashes. This appears to be caused by line 53 of ExperienceOrbEntityMixin calling Random.nextInt(0), causing an IllegalArgumentException
[crash report - intermediary with just trinkets.txt](https://github.com/emilyalexandra/trinkets/files/6830934/crash-2021-07-16_23.22.05-server.txt)
[crash report - named with the aether reborn mod.txt](https://github.com/emilyalexandra/trinkets/files/6830948/crash-2021-07-16_23.16.46-server.txt)

**Comment by Jack-Papel** [comment]
Can confirm

**Comment by emilyalexandra** [comment]
Astute analysis, fixed in 3.0.2
