### ISSUE TITLE
Mod conflict (NyfsQuiver)

### ISSUE THREAD

**Issue by ShainCasterway** [emilyalexandra/trinkets#110]
Version: 
Trinkets 3.0.2

Mods in question:
NyfsQuiver (https://github.com/Nyfaria/NyfsQuiver) v0.2.6
Elytra Trinket (Fabric) (https://www.curseforge.com/minecraft/mc-mods/elytra-trinket-fabric) v2.0.1
Trinket of Undying (Fabric) (https://www.curseforge.com/minecraft/mc-mods/trinket-of-undying-fabric) v2.0.0
Trinket Shulker Boxes (Fabric) (https://www.curseforge.com/minecraft/mc-mods/trinket-shulker-boxes-fabric) v2.0.0

Observed Behavior:
The arrow slot disappears when an elytra or totem is equipped but the arrows icon stays (bottom left of the screenshots)

Expected behavior: 
The slot shouldn't disappear

Steps to Reproduce:
1) equip a quiver
2) equip an elytra or a totem
(works the other way around too)

![Screenshot 2021-07-25 165441](https://user-images.githubusercontent.com/87939914/127482308-c9fc4658-5093-4dc7-8d72-4f056cf8e004.png)
![Screenshot 2021-07-25 165549](https://user-images.githubusercontent.com/87939914/127482368-49e79a62-5baa-4937-8b4a-3eb02d2fea72.png)
![Screenshot 2021-07-29 125953](https://user-images.githubusercontent.com/87939914/127482387-9e6222ce-372b-4b4a-ba27-eec37ee829ea.png)
![Screenshot 2021-07-29 130032](https://user-images.githubusercontent.com/87939914/127482397-4e489363-5c50-4d01-a681-4bb76863c38a.png)

in the first 2 screenshots i was also using BackSlot (https://www.curseforge.com/minecraft/mc-mods/backslot) v1.2.0 but that doen't use Trinkets and it's not influent to the bug
Interesting behavior:
Equipping a shulker box doesn't make the arrow slot disappear
![Screenshot 2021-07-29 132057](https://user-images.githubusercontent.com/87939914/127483402-ee88ebac-4f8e-420b-8d44-e87bbf6f6f4e.png)
![Screenshot 2021-07-29 132121](https://user-images.githubusercontent.com/87939914/127483415-e1234dac-f293-4d72-b2c2-fba6e717fc1b.png)
Hope I explained the bug in detail. Could you please fix it by any chance?

**Comment by emilyalexandra** [comment]
This seems to be a texture binding rendering issue on the part of NyfsQuiver, I don't believe trinkets is responsible for this issue, I'd recommend reposting this detailed bug report to them so they can figure it out, thanks!
