### ISSUE TITLE
Trinkets Overwrites Backslot 

### ISSUE THREAD

**Issue by Art1xs** [emilyalexandra/trinkets#111]
With the trinkets mod installed, the backslot mod is covered by trinkets slots. Here is a picture so you know what I mean 
![2021-07-30_11 54 39](https://user-images.githubusercontent.com/63431899/127679783-94b847f0-35bd-407f-a476-58f3bde2dbfb.png)

This bug (or feature) does not allow anything in the back slots, but does allow trinkets.

**Comment by emilyalexandra** [comment]
This issue is the fault of backslot. The correct solution to this problem would be for backslot to be using trinkets to maintain compatibility, but for some unknown reason they roll their own invasive vanilla screen slot addition. I'm sorry for the hassle caused by this ordeal.

**Comment by Birgliss** [comment]
alternatively, Backslots has a config that allows you to control the position of its slots  
you, as the player, can move the slots elsewhere in the gui to use them

**Comment by Art1xs** [comment]
> This issue is the fault of backslot. The correct solution to this problem would be for backslot to be using trinkets to maintain compatibility, but for some unknown reason they roll their own invasive vanilla screen slot addition. I'm sorry for the hassle caused by this ordeal.

Don't worry about it, I realized that the backslot config let's me move where the slots go. I fixed the positioning and now everything is functional. Thank you!
