### ISSUE TITLE
Allow configuration of cape slot

### ISSUE THREAD

**Issue by i509VCB** [emilyalexandra/trinkets#13]
I've noticed there is no way to disable placing the elytra within the capes slot. Even though this is a well liked feature I feel a way to configure it would be a good option for mod packs which wish to use trinkets for other reasons but want a harder balance in their packs.

**Comment by emilyploszaj** [comment]
This is something I'll work on adding. I think there are 4-5 mixins (several redirects) that are in place to allow the elytra to function in the cape slot. This is a feature (among several others) I plan on having in the future update that greatly expands trinkets' configuration options to modpack makers.

**Comment by supersaiyansubtlety** [comment]
I'd like to add that separate configuration for elytra enabled in cape slot and in chest slot would be ideal. 
Specifically the configuration I'd use would be elytra only in chest slot, but cosmetics can be worn in cape slot. 
So it'd be something like
```
capeSlot = true
elytraAllowedInCapeSlot = false
elytraAllowedInChestSlot = true
```

**Comment by Hugman76** [comment]
Is this issue still a thing?

**Comment by emilyalexandra** [comment]
the scope of the issue has slightly changed, in the 3.0.0 release of trinkets, it will not be a config option, but instead will simply not exist, making trinkets a pure api, I'll release a separate mod that has this behavior, it is currently like this on the 3.0.0 branch, but it's not released so I've not removed the issue

**Comment by Arbee4ever** [comment]
When are you going to release that? I need that for my mod ^^

**Comment by emilyalexandra** [comment]
the 3.0.0 branch has this feature and will be the first release of 1.17

**Comment by dMoonShadowElf** [comment]
can u please release a fork for 1.16.4
i need this mod api for other mods but this feature causes problems with another mod 
maybe not even a offical release just a fork u can only download from here

**Comment by dMoonShadowElf** [comment]
i also don't wanna have to delete my world when 1.17 comes cause this mod forces a update

**Comment by Skylortrexler** [comment]
> i also don't wanna have to delete my world when 1.17 comes cause this mod forces a update

I mean, you should start over when moving to 1.17 anyway because of the massive changes to the world generation.
