### ISSUE TITLE
client class mixin in common mixin category

### ISSUE THREAD

**Issue by Linguardium** [emilyalexandra/trinkets#29]
https://github.com/emilyploszaj/trinkets/blob/a5bb044e495ee7029f2b5e31cf8cdf293a85b229/src/main/resources/trinkets.mixins.json#L9

ClientPlayerEntityMixin class targeted does not exist on dedicated servers

**Comment by papuSpartan** [comment]
Pretty sure this is what was crashing my server as well. Also for some reason just can't use elytras at all for some reason, even after removing fallflyinglib and conflicting mods.
