### ISSUE TITLE
[Suggestion] Vanilla-like slots

### ISSUE THREAD

**Issue by AllyTally** [emilyalexandra/trinkets#50]
The title of this issue is vague because otherwise it'd be huge, haha

While working on [my mod VanitySlots](https://github.com/AllyTally/VanitySlots), I noticed a few things I had to find workarounds for:

1. There doesn't seem to be an easy way to let already existing items enter slots. What if you want to have a slot that can have whatever in it? For example, if I want to be able to put slimeballs in a slot, I would have to write a mixin. This isn't too bad, but for stuff like armor...
2. There should be a way to make a new slot act like vanilla slots. Without this, you have to write a mixin for things like ArmorItem.
3. There should be some sort of way to choose whether shift-clicking an item goes into the vanilla slot first instead of the new slot. For example, if you add a slot in the chest group, and you shift-click, and the item can go in either the custom slot or the vanilla chestplate slot, there should be a way to make it go into the vanilla chestplate slot if it's empty, instead of going into the custom slot first.

**Comment by emilyalexandra** [comment]
All of these things actually exist (except part of 3).
When you define a slot you can define how it chooses to validate items, see the Trinkets `chest:cape` slot and how it allows elytra: https://github.com/emilyalexandra/trinkets/blob/master/src/main/java/dev/emi/trinkets/TrinketsMain.java#L23
Slots also have a property called `disableQuickMove` which is public and you can modify to disable shift clicking into that slot.
The only thing Trinkets does *not* have is more precise control over which items can and can't be shift clicked into slots, but that's a low priority issue as I'm currently rewriting trinkets for its 3.0.0 version which will include a lot of changes by itself

**Comment by AllyTally** [comment]
Alright, thank you!
