### ISSUE TITLE
[3.0.0] Only allow one Trinket to be equipped in a slot by default

### ISSUE THREAD

**Issue by florensie** [emilyalexandra/trinkets#59]
In both current versions of Trinkets you can stack multiple items in one slot. I think it makes sense for most usages of the library that a slot only allows one trinket to fit. When stacking should be allowed this could be enabled on per-slot or per-trinket basis. To me this seems better than having to disable it for all other trinkets.

The main use case for stacking trinkets would be items like heart containers.

**Comment by emilyalexandra** [comment]
I actually have a heart container mod that uses stacking to stack up to 10 into a single slot, I can't think of many items that would want an unlimited stack but a limited slot. Also, for the record, limiting stack sizes into slots is **impossible** if I also want to support shift clicking, it's a vanilla bug that can't be fixed without a very intrusive set of modifications.

**Comment by TheIllusiveC4** [comment]
I'm curious as to what issue this would resolve or is there a use-case that needs this kind of behavior? It seems like an arbitrary limitation on the API otherwise.

**Comment by florensie** [comment]
I need some sleep, my brain is shrinking by the minute. I somehow forgot about setting a stack size limit on your item. There's still a use case for this but it's probably not worth the effort and shouldn't be default either way.
