### ISSUE TITLE
[3.0.0] Allow entity type tags for entity slot loader

### ISSUE THREAD

**Issue by florensie** [emilyalexandra/trinkets#63]
Example:
```json
"entities": ["#skeletons"],
"slots": [
  "head/hat",
  "chest/necklace",
  "legs/belt",
  "feet/shoes"
]
```
This should probably even replace the array behavior completely and require an entity type tag if multiple entity types are desired:
```json
"entities": "#skeletons",
"slots": [...]
```

Useful vanilla implementation reference:
- `data/minecraft/tags/entity_types/`
- `net.minecraft.predicate.entity.EntityTypePredicate`

**Comment by emilyalexandra** [comment]
This has been fixed in #64, I agreed with C4 though on the concept of keeping the entity list, removing it has no benefit and would likely just frustrate some people.
