### ISSUE TITLE
Slot desync with multiple trinket mods

### ISSUE THREAD

**Issue by florensie** [emilyalexandra/trinkets#68]
There appears to be some kind of desync where client and server might have their slots ids assigned to trinket slots ids/groups in a different order. I'm not entirely sure that this is what happening but you can see the full issue here: https://github.com/florensie/artifacts-fabric/issues/20

**Comment by emilyalexandra** [comment]
this shouldn't be an issue in 3.0.0 since they use synced data, but I'm not sure how to correct this in 1.16, server/client registry order should be the same and I'm not sure how it's getting desynced

**Comment by emilyalexandra** [comment]
a bandaid patch for this could be sorting the arrays for slots and slot groups every time one is added... though that seems pretty silly, I'll have to think about this some more

**Comment by Lindoff** [comment]
![mds](https://user-images.githubusercontent.com/81748186/113278604-6afa8800-92e2-11eb-9b00-204e2b8bfce4.PNG)
So I am playing on a server with my friends, I sent a picture of the mods we have, but for some reason when I place an artifact in a trinket slot it all just desyncs and buggs out, when I am to place something on the necklace slot it goes suddenly to the cape slot, same with belt slot except that one goes to the necklace. Also when I go through a netherportal, place a boat or fire a rocket  whatever I have in my hotbar slot 1 just dissapears and I have to open my inventory and click on that slot to get the item back. Only I have that problem on the server and none of my friends have it, also it only happens on the server and it doesn't happen on a singelplayer world.

**Comment by emilyalexandra** [comment]
The common case in these issues is both times artifacts is present. I'm going to have to take a look at the repo to see if it's something they can correct or if it's actually a problem with trinkets.

**Comment by florensie** [comment]
I remember having so pretty concerning mixins to prevent equipping two of the same artifacts. Not sure how it would create an items moving around issue but I'll look into it either way.

**Comment by eehunter** [comment]
Not sure if this helps, but I had this issue when Artifacts was installed on the client but not the server. I fixed it by removing Artifacts completely, as it had a server-side conflict with another mod anyway, and was only on the client because we were using a modified version of AoF3, and I didn't think to have the players remove it until the glitch came up.

**Comment by emilyalexandra** [comment]
oh. yeah, the mods using trinkets have to be synced on both the client and server. I'm not sure this is the entire issue, but fixes one of the specific cases

**Comment by florensie** [comment]
I released an update for Artifacts that removes the questionable mixins (I didn't really need them anymore). If issues still occur on v3.2.0 then at least we can pin-point it to Trinkets.

**Comment by Lindoff** [comment]
Sorry for the late reply, I was busy but I'll go ahead and try installing the update to see it it works, also the owner will make sure to update it on the server too. Also since last it appears that one more person on the server had the same problem with the mods.

**Comment by florensie** [comment]
Strange that it only happens to some people, and then stays like that consistently. Could it be something loaded from player nbt @emilyalexandra?

**Comment by Lindoff** [comment]
The update didn't work, also reseting the player data in the files didn't work either for us. This is really weird since it doesn't happen in singelplayer or on another creative server we created for building on before building on the actual server.
