### ISSUE TITLE
game crash with optifabric mod installed

### ISSUE THREAD

**Issue by BerkyOnline** [emilyalexandra/trinkets#69]
The game crashes on start up  whenever I have the optifabric and optifine mods installed along side the artifacts mod. I assume its a compatibility issue but I'm not sure why that would be the case. It worked fine after I took out just the optifabric mod, and just to be safe I doubled checked with every other mod that I had in my mod folder.

here is the crash report
[Crash Report Artifact+Optifabric.txt](https://github.com/emilyalexandra/trinkets/files/6174776/Crash.Report.Artifact%2BOptifabric.txt)

**Comment by emilyalexandra** [comment]
Optifabric is not supported.

**Comment by florensie** [comment]
Also, it's obviously a crash with Artifacts and not Trinkets (it's fixed btw). Trinkets doesn't do any out of the ordinary stuff to rendering.
