### ISSUE TITLE
Hide slots for specific players.

### ISSUE THREAD

**Issue by eehunter** [emilyalexandra/trinkets#70]
Would it be possible to add a way to disable certain slots for certain players, as in hide them in the inventory and prevent rendering/ticking/etc.? I'm mainly thinking about this for the purpose of Origins compatibility, as in trinket slots that are only available to specific origins.

**Comment by CodeF53** [comment]
You 100% couldn't prevent them from ticking.
Chime is clientside.

**Comment by eehunter** [comment]
The rendering and ticking part isn't really necessary for what I'm trying to do, as I can handle that part on my end. It would just be preferable to be able to hide the slots in the inventory.

**Comment by emilyalexandra** [comment]
Trinkets 3.0.0 will have a more malleable slot system for stuff like this. Unfortunately, it is out of scope to bring back to 1.16, so it's going to be necessary to wait until 1.17 proper

**Comment by eehunter** [comment]
Ok.

**Comment by emilyalexandra** [comment]
Doable with generic EAMs in 3.0.0
