### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by Rubyz67** [emilyalexandra/trinkets#73]
can u make it that u can disable trinkets from showing just like curious?

**Comment by MitztheKat** [comment]
I kind of wish this was reality too.
If I could toggle in settings the ability to see trinkets, that'd work too. Even if it's just client-side IE everyone can see everyone's trinkets but trinkets aren't visible to me.

**Comment by emilyalexandra** [comment]
This is out of scope for trinkets
