### ISSUE TITLE
Dedicated server slot desync issues

### ISSUE THREAD

**Issue by profjb58** [emilyalexandra/trinkets#79]
Some weird slot desync stuff going on, possibly related to #68 happens using the latest version of trinkets

**Video**
https://user-images.githubusercontent.com/46009144/116002170-5b741380-a5f0-11eb-882c-3e2525899899.mp4

**Comment by emilyalexandra** [comment]
Can I get a modlist and confirmation that all mods are installed properly and client and server?

**Comment by profjb58** [comment]
Of course yes.
The pack is basically AOF3 2.7.1 with the following mods included on-top: https://github.com/The-Tiny-Taters/TTTM-AOF (see README.md)

Trinkets 2.6.7 is definitely installed on both the server and client as well, just checked

**Comment by profjb58** [comment]
The following additional mods: `SimpleAngelRing` and `Through the looking glass` both add trinkets but they all add the same version of Trinkets `2.6.7`
