### ISSUE TITLE
Cardinal Components security certificate expired

### ISSUE THREAD

**Issue by Ninja202** [emilyalexandra/trinkets#80]
When trying to build i get the following issue, and it looks like the security certificate expired on Mon Apr 26 16:05:42 MDT 2021 or Cardinal Components v2.5.0 does not exist. I believe that upgrading to Cardinal components 2.6.0 might work. Below is the error message outputed by IDEA.
```
Could not resolve all files for configuration ':modCompileClasspath'.
   > Could not resolve io.github.onyxstudios.Cardinal-Components-API:cardinal-components-base:2.5.0.
     Required by:
         project : > dev.emi:trinkets:2.6.7
      > Could not resolve io.github.onyxstudios.Cardinal-Components-API:cardinal-components-base:2.5.0.
         > Could not get resource 'https://maven.abusedmaster.xyz/io/github/onyxstudios/Cardinal-Components-API/cardinal-components-base/2.5.0/cardinal-components-base-2.5.0.pom'.
            > Could not GET 'https://maven.abusedmaster.xyz/io/github/onyxstudios/Cardinal-Components-API/cardinal-components-base/2.5.0/cardinal-components-base-2.5.0.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.0/userguide/build_environment.html#gradle_system_properties
                  > PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
```

**Comment by Ninja202** [comment]
I am probably missing something but i don't understand how to compile my mod, gradle says that it cant resolve the CCA dependancy

**Comment by PureFallen** [comment]
> 
> 
> I am probably missing something but i don't understand how to compile my mod, gradle says that it cant resolve the CCA dependancy

Add a Maven repository that includes the CCA Version you are looking for, then implement and include CCA as dependancy.
I currently use 2.8.3 for that and get it from Ladysnake newest maven:

`
repositories {
    [...]

    maven {
        name = "Ladysnake Mods"
        url = 'https://ladysnake.jfrog.io/artifactory/mods'
    }
}

dependencies {
    [...]

    modImplementation "io.github.onyxstudios.Cardinal-Components-API:cardinal-components-base:2.8.3"
    include "io.github.onyxstudios.Cardinal-Components-API:cardinal-components-base:2.8.3"
    modImplementation "io.github.onyxstudios.Cardinal-Components-API:cardinal-components-entity:2.8.3"
    include "io.github.onyxstudios.Cardinal-Components-API:cardinal-components-entity:2.8.3"
}
`

That is atleast what i am using for 1.16.5 testing for now. However, i currently paused and wait for the trinket recode of 1.17 to finish.
