### ISSUE TITLE
String comparison using == instead of equals()?

### ISSUE THREAD

**Issue by Mari023** [emilyalexandra/trinkets#81]
While implementing showing Trinkets slots on an Inventory, I stumbled upon String comparisons using == or !=
Is there a reason why you do this or is it just an oversight?
[example](https://github.com/emilyalexandra/trinkets/blob/5a846f68eb73868b03e83b3151ee518b364a8026/src/main/java/dev/emi/trinkets/mixin/InventoryScreenMixin.java#L171)

**Comment by emilyalexandra** [comment]
Technically this is an oversight from some old code but also it's never actually going to cause any problems, since it'll always be comparing the same reference as it doesn't mutate strings
