### ISSUE TITLE
World loading issue

### ISSUE THREAD

**Issue by AmyMialee** [emilyalexandra/trinkets#82]
For some reason trinkets is causing worlds to be unable to load, sometimes crashing with attached report.

[crash-2021-05-02_17.38.06-server.txt](https://github.com/emilyalexandra/trinkets/files/6411815/crash-2021-05-02_17.38.06-server.txt)

When it doesn't crash it gets this far and then stops completely.

![image](https://user-images.githubusercontent.com/10999535/116820598-d8ae0400-ab6d-11eb-8fbb-5cd6aa6980fa.png)

**Comment by AmyMialee** [comment]
Turns out it works fine when I downgrade to fabric-api-0.32.5 (rather than 0.34.0).

**Comment by gniftygnome** [comment]
It's a known issue requiring the included copy of Cardinal Components to be upgraded...

[Cardinal Components API issue 84](https://github.com/OnyxStudios/Cardinal-Components-API/issues/84)

**Comment by RDKRACZ** [comment]
Can we get a new release of Trinkets (with updated CCA) or, better, without nesting CCA (to avoid issues like this in the future also this is a popular dependency so nesting it doesn't make sense)?

**Comment by emilyalexandra** [comment]
CCA encourages JIJing, fabric allows you to override the dependency by simply putting an updated version in your mods folder, so you can update CCA if you want to use a more updated fapi
