### ISSUE TITLE
Requesting Compiling Assistance

### ISSUE THREAD

**Issue by MitztheKat** [emilyalexandra/trinkets#84]
Hi,
I am attempting to try and compile this so I can test some of my ideas.
Right now, I just have the base files, and as a newbie minecraft coder (not of coding in general) I don't know where to get started on compiling.
My goal is to add a toggle to make trinkets visible or not, in general. It'd be client-side, and I think I have some code to base it off of but I cannot get it to compile.
I'm using Visual Studio Code, if you could tell me how you compile Trinkets, that'd be great.

**Comment by supsm** [comment]
Run `./gradlew build` (not windows) or `gradlew build` (windows). Compiled jars should be in `build/libs` (get the one without -dev or -sources))

**Comment by emilyalexandra** [comment]
My issues page is not a great place to learn the basics of minecraft modding, I suggest you look up fabric documentation instead
