### ISSUE TITLE
old cca dependency breaks with newer fabric version

### ISSUE THREAD

**Issue by oliwoli** [emilyalexandra/trinkets#85]
Using a relatively new fabric version, I noticed that the **cardinal components api v2.5.0** dependency causes minecraft to freeze during world generation/loading.
Here's the full log file
[latest.log](https://github.com/emilyalexandra/trinkets/files/6460583/latest.log)

This should get fixed when updating the cca dependency to a version above 2.5.0 (I only tested with 2.8.2 which fixed the problem)

Note that there already is a pull request #71 by @florensie that would update the dependency to 2.7.13

**How to reproduce:**
- Install trinkets with fabric API v0.34.1
- create a new world

**Comment by PinkGoosik** [comment]
emi please 🙏

**Comment by emilyalexandra** [comment]
This can be solved temporarily by simply installing a modern version of cardinal components in your mods folder

**Comment by PinkGoosik** [comment]
But i cant use it in dev env

**Comment by PinkGoosik** [comment]
oh nvm im stupid
