### ISSUE TITLE
trinket slot doesnt work with BetterEnd's armored elytra

### ISSUE THREAD

**Issue by SpinnyBoiii** [emilyalexandra/trinkets#86]
idk who's side it's on, posted an issue at the BetterEnd mod and they said not a vanilla slot->problem not on our side.
you can equip it in the trinket slot(shift clicking prioritizes it even), just cant actually open it(and with mods that show durability, doesnt even register as equipped)

**Comment by emilyalexandra** [comment]
Trinkets is a standard accessory api, other mods are responsible for providing compat if they desire it.
