### ISSUE TITLE
1.17 support when?

### ISSUE THREAD

**Issue by kristibektashi** [emilyalexandra/trinkets#94]

**Comment by LucilleTea** [comment]
It's already released ??
GitHub: https://github.com/emilyalexandra/trinkets/releases/tag/3.0.0
Modrinth: https://modrinth.com/mod/trinkets
Curse: https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric

**Comment by kristibektashi** [comment]
Bruh I'm blind
