### ISSUE TITLE
I didn't have any additional slot

### ISSUE THREAD

**Issue by Bakagema00** [emilyalexandra/trinkets#95]
there's no additional equip slot

**Comment by emilyalexandra** [comment]
This is intended behavior, unless you add mods that add slots, or add them with a datapack, trinkets isn't going to add slots.

**Comment by Bakagema00** [comment]
Ouh,okay I'll search for the mod...thank you very much....sorry

**Comment by Bakagema00** [comment]
But there's no such mod for 1.17

Backslot mod crash if I launch the game..
